name: Build Flutter APK

on:
  push:
    branches:
      - main # Déclencher sur les pushs dans la branche principale
  pull_request:
    branches:
      - main # Déclencher pour les pull requests vers la branche principale

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérification du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Installation de Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable' # Version Flutter (stable, beta ou un numéro spécifique)

    # Étape 3 : Cache des dépendances Flutter
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    # Étape 4 : Packages Flutter
    - name: Install Flutter dependencies
      run: flutter pub get

    # Étape 5 : Construire l'APK en mode release
    - name: Build APK
      run: flutter build apk --release

    # Étape 6 : Enregistrer l'APK généré comme artefact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
